name: User Onboarding/Offboarding
description: Template for requesting user onboarding or offboarding actions
title: "[User Management]: "
labels: ["user-management", "automation"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Management Request

        Please use this template to request user onboarding or offboarding.

        ### Action Required

        - [ ] Onboard
        - [ ] Offboard

        ### User Details

        - **Username or Email**: 
        - **Role**: 
          - Options: Admin, Write, Read
        - **Target**: 
          - Specify the organization or repository (e.g., `owner/repo`)

        ### Additional Information

        Provide any additional context or information here.

        **Instructions**:
        1. Select the action required (Onboard or Offboard).
        2. Fill in the user details and target.
        3. Submit the issue.
        4. Add a comment to trigger the automation:
           - `/onboard <filename>.csv` for onboarding
           - `/offboard <filename>.csv` for offboarding